package com.example.mcservermonitor.model

class BlockUtil {
    val blockTypes = mutableMapOf<String, Block>()

    init {
        for (blockType in Block.values()) {
            blockTypes[blockType.mcName] = blockType
        }
    }
}

enum class Block(val mcName: String, val textureAtlasPos: BlockTexturePositions) {
    AIR("minecraft:air", BlockTexturePositions(-1, -1)),
    CAVE_AIR("minecraft:cave_air", BlockTexturePositions(-1, -1)),
    STONE("minecraft:stone", BlockTexturePositions(1, 0)),
    GRANITE("minecraft:granite", BlockTexturePositions(14, 8)),
    POLISHED_GRANITE("minecraft:polished_granite", BlockTexturePositions(15, 8)),
    DIORITE("minecraft:diorite", BlockTexturePositions(14, 9)),
    POLISHED_DIORITE("minecraft:polished_diorite", BlockTexturePositions(15, 9)),
    ANDESITE("minecraft:andesite", BlockTexturePositions(14, 7)),
    POLISHED_ANDESITE("minecraft:polished_andesite", BlockTexturePositions(15, 7)),
    GRASS_BLOCK("minecraft:grass_block", BlockTexturePositions(3, 0, 0, 0, 2, 0)),
    DIRT("minecraft:dirt", BlockTexturePositions(2, 0)),
    COARSE_DIRT("minecraft:coarse_dirt", BlockTexturePositions(2, 0)),
    PODZOL("minecraft:podzol", BlockTexturePositions(2, 0)),
    COBBLESTONE("minecraft:cobblestone", BlockTexturePositions(0, 1)),
    OAK_PLANKS("minecraft:oak_planks", BlockTexturePositions(4, 0)),
    SPRUCE_PLANKS("minecraft:spruce_planks", BlockTexturePositions(12, 0)),
    BIRCH_PLANKS("minecraft:birch_planks", BlockTexturePositions(8, 0)),
    JUNGLE_PLANKS("minecraft:jungle_planks", BlockTexturePositions(6, 0)),
    ACACIA_PLANKS("minecraft:acacia_planks", BlockTexturePositions(10, 0)),
    DARK_OAK_PLANKS("minecraft:dark_oak_planks", BlockTexturePositions(14, 0)),
    BEDROCK("minecraft:bedrock", BlockTexturePositions(7, 3)),
    SAND("minecraft:sand", BlockTexturePositions(2, 1)),
    RED_SAND("minecraft:red_sand", BlockTexturePositions(10, 15)),
    GRAVEL("minecraft:gravel", BlockTexturePositions(3, 1)),
    GOLD_ORE("minecraft:gold_ore", BlockTexturePositions(0, 2)),
    IRON_ORE("minecraft:iron_ore", BlockTexturePositions(1, 2)),
    COAL_ORE("minecraft:coal_ore", BlockTexturePositions(2, 2)),
    OAK_LOG("minecraft:oak_log", BlockTexturePositions(4, 1, 5, 1)),
    SPRUCE_LOG("minecraft:spruce_log", BlockTexturePositions(12, 1, 13, 1)),
    BIRCH_LOG("minecraft:birch_log", BlockTexturePositions(8, 1, 9, 1)),
    JUNGLE_LOG("minecraft:jungle_log", BlockTexturePositions(6, 1, 7, 1)),
    ACACIA_LOG("minecraft:acacia_log", BlockTexturePositions(10, 1, 11, 1)),
    DARK_OAK_LOG("minecraft:dark_oak_log", BlockTexturePositions(14, 1, 15, 1)),
    STRIPPED_OAK_LOG("minecraft:stripped_oak_log", BlockTexturePositions(5, 0)),
    STRIPPED_SPRUCE_LOG("minecraft:stripped_spruce_log", BlockTexturePositions(13, 0, 13, 1)),
    STRIPPED_BIRCH_LOG("minecraft:stripped_birch_log", BlockTexturePositions(9, 0)),
    STRIPPED_JUNGLE_LOG("minecraft:stripped_jungle_log", BlockTexturePositions(7, 0, 7, 1)),
    STRIPPED_ACACIA_LOG("minecraft:stripped_acacia_log", BlockTexturePositions(11, 0, 11, 1)),
    STRIPPED_DARK_OAK_LOG("minecraft:stripped_dark_oak_log", BlockTexturePositions(15, 0, 15, 1)),
    STRIPPED_OAK_WOOD("minecraft:stripped_oak_wood", BlockTexturePositions(5, 0)),
    STRIPPED_SPRUCE_WOOD("minecraft:stripped_spruce_wood", BlockTexturePositions(13, 0)),
    STRIPPED_BIRCH_WOOD("minecraft:stripped_birch_wood", BlockTexturePositions(9, 0)),
    STRIPPED_JUNGLE_WOOD("minecraft:stripped_jungle_wood", BlockTexturePositions(7, 0)),
    STRIPPED_ACACIA_WOOD("minecraft:stripped_acacia_wood", BlockTexturePositions(11, 0)),
    STRIPPED_DARK_OAK_WOOD("minecraft:stripped_dark_oak_wood", BlockTexturePositions(15, 0)),
    OAK_LEAVES("minecraft:oak_leaves", BlockTexturePositions(16, 0)),
    SPRUCE_LEAVES("minecraft:spruce_leaves", BlockTexturePositions(17, 0)),
    BIRCH_LEAVES("minecraft:birch_leaves", BlockTexturePositions(16, 1)),
    JUNGLE_LEAVES("minecraft:jungle_leaves", BlockTexturePositions(17, 1)),
    ACACIA_LEAVES("minecraft:acacia_leaves", BlockTexturePositions(16, 0)),
    DARK_OAK_LEAVES("minecraft:dark_oak_leaves", BlockTexturePositions(16, 0)),
    LAPIS_ORE("minecraft:lapis_ore", BlockTexturePositions(5, 2)),
    LAPIS_BLOCK("minecraft:lapis_block", BlockTexturePositions(5, 3)),
    SANDSTONE("minecraft:sandstone", BlockTexturePositions(6, 15,5, 15)),
    CHISELED_SANDSTONE("minecraft:chiseled_sandstone", BlockTexturePositions(9, 15,5, 15)),
    CUT_SANDSTONE("minecraft:cut_sandstone", BlockTexturePositions(8, 15,5, 15)),
    NOTE_BLOCK("minecraft:note_block", BlockTexturePositions(16, 4)),
    GRASS("minecraft:grass", BlockTexturePositions(-1, -1)),
    WHITE_WOOL("minecraft:white_wool", BlockTexturePositions(1, 13)),
    ORANGE_WOOL("minecraft:orange_wool", BlockTexturePositions(1, 12)),
    MAGENTA_WOOL("minecraft:magenta_wool", BlockTexturePositions(1, 11)),
    LIGHT_BLUE_WOOL("minecraft:light_blue_wool", BlockTexturePositions(1, 10)),
    YELLOW_WOOL("minecraft:yellow_wool", BlockTexturePositions(1, 9)),
    LIME_WOOL("minecraft:lime_wool", BlockTexturePositions(1, 8)),
    PINK_WOOL("minecraft:pink_wool", BlockTexturePositions(1, 7)),
    LIGHT_GRAY_WOOL("minecraft:light_gray_wool", BlockTexturePositions(0, 13)),
    CYAN_WOOL("minecraft:cyan_wool", BlockTexturePositions(0, 12)),
    PURPLE_WOOL("minecraft:purple_wool", BlockTexturePositions(0, 11)),
    BLUE_WOOL("minecraft:blue_wool", BlockTexturePositions(0, 10)),
    BROWN_WOOL("minecraft:brown_wool", BlockTexturePositions(0, 9)),
    GREEN_WOOL("minecraft:green_wool", BlockTexturePositions(0, 8)),
    RED_WOOL("minecraft:red_wool", BlockTexturePositions(0, 7)),
    BLACK_WOOL("minecraft:block_wool", BlockTexturePositions(0, 14)),
    POPPY("minecraft:poppy", BlockTexturePositions(-1, -1)),
    GOLD_BLOCK("minecraft:gold_block", BlockTexturePositions(0, 3)),
    IRON_BLOCK("minecraft:iron_block", BlockTexturePositions(1, 3)),
    SMOOTH_RED_SANDSTONE("minecraft:smooth_red_sandstone", BlockTexturePositions(11, 15)),
    SMOOTH_SANDSTONE("minecraft:smooth_sandstone", BlockTexturePositions(5, 15)),
    SMOOTH_STONE("minecraft:smooth_stone", BlockTexturePositions(0, 15)),
    BRICKS("minecraft:bricks", BlockTexturePositions(15, 14)),
    DIAMOND_ORE("minecraft:diamond_ore", BlockTexturePositions(3, 2)),
    DIAMOND_BLOCK("minecraft:diamond_block", BlockTexturePositions(3, 3)),
    CRAFTING_TABLE("minecraft:crafting_table", BlockTexturePositions(8, 3, 8, 2)),
    FARMLAND("minecraft:farmland", BlockTexturePositions(2, 0)),
    REDSTONE_ORE("minecraft:redstone_ore", BlockTexturePositions(4, 2)),
    CLAY("minecraft:clay", BlockTexturePositions(1, 1)),
    PUMPKIN("minecraft:pumpkin", BlockTexturePositions(7, 6, 7, 5)),
    CARVED_PUMPKIN("minecraft:carved_pumpkin", BlockTexturePositions(7, 6, 7, 5)),
    NETHERRACK("minecraft:netherrack", BlockTexturePositions(16,7)),
    STONE_BRICKS("minecraft:stone_bricks", BlockTexturePositions(1,15)),
    MOSSY_STONE_BRICKS("minecraft:mossy_stone_bricks", BlockTexturePositions(2,15)),
    CRACKED_STONE_BRICKS("minecraft:cracked_stone_bricks", BlockTexturePositions(3,15)),
    CHISELED_STONE_BRICKS("minecraft:chiseled_stone_bricks", BlockTexturePositions(4,15)),
    MELON("minecraft:melon", BlockTexturePositions(15,11, 14, 11)),
    REDSTONE_LAMP("minecraft:redstone_lamp", BlockTexturePositions(8, 2)),
    REDSTONE_BLOCK("minecraft:redstone_block", BlockTexturePositions(4, 3)),
    QUARTZ_BLOCK("minecraft:quartz_block", BlockTexturePositions(16, 9)),
    COAL_BLOCK("minecraft:coal_block", BlockTexturePositions(2, 3)),
    PRISMARINE("minecraft:prismarine", BlockTexturePositions(6, 12)),
    BONE_BLOCK("minecraft:bone_block", BlockTexturePositions(15, 10, 14, 10)),


    WATER("minecraft:water", BlockTexturePositions(30, 0)),
    LAVA("minecraft:lava", BlockTexturePositions(31, 0)),
    NETHER_PORTAL("minecraft:nether_portal", BlockTexturePositions(29, 0)),

}

data class BlockTexturePositions(
    val sideX: Int, val sideY: Int,
    val topX: Int = sideX, val topY: Int = sideY,
    val bottomX: Int = topX, val bottomY: Int = topY
)